#!/usr/bin/env python3
from __future__ import annotations
from pathlib import Path
from urllib.parse import urlparse
from bs4 import BeautifulSoup
from collections import defaultdict
import json,re

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'docs/CONTENT-GRAPH-REPORT-v0.6.7.md'
HOST='bezpecnaelektrika.sk'
EXCLUDE={'/hladat/','/404/'}

def rel_url(path:Path)->str:
    rel=path.relative_to(ROOT).as_posix()
    if rel=='index.html': return '/'
    if rel=='404.html': return '/404/'
    if rel.endswith('/index.html'): return '/'+rel[:-10]
    return '/'+rel

def ptype(url:str)->str:
    if url=='/': return 'home'
    if url=='/revizie/': return 'service'
    if url=='/meranie/': return 'measurement'
    if url.startswith('/poradna/') and url!='/poradna/': return 'poradna'
    if url.startswith('/glosar/') and url!='/glosar/': return 'kb'
    if url.startswith('/podcast/') and url!='/podcast/': return 'podcast'
    if url.startswith('/novinky/') and url!='/novinky/': return 'news'
    return 'hub/utility'

def clean_target(href:str)->str|None:
    if not href or href.startswith(('#','mailto:','tel:','javascript:')): return None
    if href.startswith('http'):
        u=urlparse(href)
        if u.netloc!=HOST: return None
        href=u.path + (('#'+u.fragment) if u.fragment else '')
    if not href.startswith('/'): return None
    path=href.split('#',1)[0].split('?',1)[0]
    if not path: return '/'
    if '.' in path.rsplit('/',1)[-1]: return None
    return path if path.endswith('/') else path+'/'

pages={}
for path in ROOT.rglob('*.html'):
    url=rel_url(path)
    soup=BeautifulSoup(path.read_text(encoding='utf-8'),'html.parser')
    robots=soup.find('meta',attrs={'name':'robots'})
    noindex=robots and 'noindex' in (robots.get('content') or '').lower()
    if noindex or url in EXCLUDE: continue
    title=soup.title.get_text(' ',strip=True) if soup.title else ''
    h1=soup.h1.get_text(' ',strip=True) if soup.h1 else ''
    main=soup.find('main')
    links=set()
    if main:
        for a in main.find_all('a',href=True):
            target=clean_target(a['href'])
            if target and target!=url: links.add(target)
    art_img=False
    for sc in soup.find_all('script',type='application/ld+json'):
        try: data=json.loads(sc.string or '')
        except Exception: continue
        graph=data.get('@graph',[]) if isinstance(data,dict) else []
        for obj in graph:
            if isinstance(obj,dict) and obj.get('@type') in {'Article','NewsArticle'} and obj.get('image'):
                art_img=True
    pages[url]={'path':path,'title':title,'h1':h1,'type':ptype(url),'out':links,'article_image':art_img}

inbound=defaultdict(set)
for src,info in pages.items():
    for dst in info['out']:
        if dst in pages: inbound[dst].add(src)

lines=[]
lines += ['# Content graph report – v0.6.7','', 'Generated by `tools/audit-content-graph.py`. Counts use links inside `<main>` so global header/footer navigation does not hide weak content relationships.','']
lines += ['## Editorial query-gap decisions','',
'- **Zs ≠ Zline:** canonical destination remains `/glosar/impedancia-poruchovej-slucky-zs/#zs-nie-je-zline`; no duplicate page.',
'- **TEST RCD:** canonical destination remains `/glosar/rcd-prudovy-chranic/#tlacidlo-test`; no duplicate page.',
'- **Nameraná hodnota vs. odborný záver:** `/meranie/` + BE-003; no duplicate page.',
'- **Čo obsahuje revízna správa:** existing `/poradna/co-obsahuje-revizna-sprava/` remains the content/definition answer.',
'- **Ako čítať revíznu správu:** separate practical intent at `/poradna/ako-citat-reviznu-spravu/`.', '']
lines += [f'## Inventory','',f'- Indexable HTML pages in graph: **{len(pages)}**',f'- Main-content internal edges: **{sum(len(v["out"] & pages.keys()) for v in pages.values())}**','']
lines += ['| URL | Type | In | Out | Article image | H1 |','|---|---:|---:|---:|:---:|---|']
for url,info in sorted(pages.items(),key=lambda x:(x[1]['type'],x[0])):
    outn=len(info['out'] & pages.keys()); inn=len(inbound[url])
    h1=info['h1'].replace('|','\\|')[:80]
    lines.append(f'| `{url}` | {info["type"]} | {inn} | {outn} | {"yes" if info["article_image"] else "—"} | {h1} |')
weak=[u for u,i in pages.items() if i['type'] in {'poradna','kb','podcast','news'} and len(inbound[u])<=1]
lines += ['','## Weakly linked expert pages','']
if weak:
    for u in sorted(weak): lines.append(f'- `{u}` — {len(inbound[u])} main-content inbound link(s)')
else: lines.append('- None at the ≤1 inbound-link threshold.')
lines += ['','## Guardrail','', 'A low link count is a review signal, not an instruction to add links mechanically. A contextual link is added only when it gives the reader a useful next step.','']
OUT.write_text('\n'.join(lines),encoding='utf-8')
print(f'CONTENT GRAPH OK · {len(pages)} pages · {sum(len(v["out"] & pages.keys()) for v in pages.values())} edges · {OUT.relative_to(ROOT)}')
