#!/usr/bin/env python3
from pathlib import Path
import argparse,sys
ROOT=Path(__file__).resolve().parents[1]
CSS=ROOT/"assets/css"
MODULES=["variables.css","base.css","layout.css","components.css","responsive.css","v040.css"]
HEADER="/* Bezpečná elektrika stylesheet\n   Generated by tools/build-css.py from source modules. Do not edit style.css directly. */\n\n"
def build():
    parts=[HEADER]
    for name in MODULES:
        parts.append(f"/* ===== {name} ===== */\n")
        parts.append((CSS/name).read_text(encoding="utf-8").strip()+"\n\n")
    return "".join(parts).rstrip()+"\n"
def main():
    ap=argparse.ArgumentParser(); ap.add_argument("--check",action="store_true"); args=ap.parse_args()
    target=CSS/"style.css"; expected=build()
    if args.check:
        actual=target.read_text(encoding="utf-8") if target.exists() else ""
        if actual!=expected:
            print("CSS BUILD CHECK FAILED · run python tools/build-css.py"); return 1
        print("CSS BUILD OK · style.css matches source modules"); return 0
    target.write_text(expected,encoding="utf-8")
    print("CSS BUILD OK · assets/css/style.css generated")
    return 0
if __name__=="__main__": sys.exit(main())
